# Generated by Django 2.2.6 on 2019-10-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('cor', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valorcompra', models.DecimalField(decimal_places=2, max_digits=19)),
                ('valovenda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('logistica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automoney.Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automoney.Equipamento')),
            ],
        ),
    ]
