# Generated by Django 2.2.6 on 2019-10-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automoney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='valorcompra',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='valovenda',
        ),
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19, verbose_name='Valor da Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valorunico',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19, verbose_name='Valor unitario'),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19, verbose_name='Valor da Venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valorunico',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19, verbose_name='Valor unitario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automoney.Equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='logistica',
            field=models.BooleanField(verbose_name='Requer Compra'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automoney.Equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compra',
        ),
        migrations.AlterModelTable(
            name='equipamento',
            table='equipamento',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='venda',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
