# Generated by Django 2.2.6 on 2019-10-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automoney', '0002_auto_20191027_0637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table=None,
        ),
        migrations.AlterModelTable(
            name='equipamento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venda',
            table=None,
        ),
    ]
